services:
  # PostgreSQL Database
  - type: pserv
    name: sim-erp-db
    env: docker
    plan: free

  # Web Service
  - type: web
    name: sim-erp-app
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sim-erp-db
          property: connectionString
      - key: SEED_ON_START
        value: false
      - key: FLASK_ENV
        value: production
    healthCheckPath: /
